# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DDfzcWKeTJwM4hx9yuZTU-ldjJwCuzB
"""

import streamlit as st
import joblib
import numpy as np

# تحميل النموذج
model = joblib.load("model.pkl")

st.title("🚗 توقع انبعاثات CO2 حسب استهلاك الوقود")

st.write("أدخل القيم الخاصة بالخصائص (features) عشان النموذج يتوقع الانبعاثات.")

# إدخال المستخدم (هنا بتكتبي عدد المدخلات اللي اتدرب عليهم النموذج)
# مثلاً لو النموذج اتدرب على 4 أعمدة كـ Features
f1 = st.number_input("الميزة الأولى (Feature 1)", value=0.0)
f2 = st.number_input("الميزة الثانية (Feature 2)", value=0.0)
f3 = st.number_input("الميزة الثالثة (Feature 3)", value=0.0)
f4 = st.number_input("الميزة الرابعة (Feature 4)", value=0.0)

# زر التنبؤ
if st.button("توقع"):
    features = np.array([[f1, f2, f3, f4]])  # تعديل عدد الأعمدة حسب تدريبك
    prediction = model.predict(features)[0]
    st.success(f"🔥 التوقع لانبعاثات CO2 هو: {prediction:.2f}")

!pip install streamlit joblib numpy